id: clips
name: Clips
version: 0.1.3
home: https://infiniticlips.com/
repo: https://github.com/azure06/clips/
installMethod: NSIS
installers:
- location: https://github.com/azure06/clips/releases/download/v0.1.3/Clips-Setup-0.1.3.exe
  sha256: d405d5042e0a23277a6fd2151c596694c1af6bd14519ee4b20619d6cdf15576e
