id: dixa-desktop-app-release
name: Dixa
version: 3.0.0.341
repo: https://github.com/dixahq/dixa-desktop-app-release/
license: Apache License 2.0
installMethod: MSI
installers:
- location: https://github.com/dixahq/dixa-desktop-app-release/releases/download/v3.0.0/dixa-3.0.0.msi
  sha256: 53b2d400166399cd7e7ea7fd5bf31e4180deb67a6d61278439d5380a95822a62
- location: https://github.com/dixahq/dixa-desktop-app-release/releases/download/v3.0.0/dixa-setup-3.0.0.exe
  sha256: 59ccec3dcea20901733a995f05631589df331b6cfd1885bb3a450ab645456a09
