id: magnifixer
name: Magnifixer
version: 10.0
home: https://www.blacksunsoftware.com/screenmagnifier.html
installMethod: Inno
installers:
- location: https://www.blacksunsoftware.com/downloads/Magnifixersetup.exe
