id: myharmony
name: MyHarmony
version: 7.7.1
home: https://myharmony.com/
installMethod: NSIS
installers:
- location: https://cdn-cx-images.dynamite.myharmony.com/software/LogitechHarmonyRemote_7.7.1-WIN-x86.exe
  sha256: 6c112a4ed845a67d26909a8ad39f766c28c55ac2831076f0b295b0c93aba1957
