id: tixati
name: Tixati
version: 2.62
home: https://tixati.com/
installMethod: Custom
installers:
- location: https://download1.tixati.com/download/tixati-2.62-1.win32-install.exe
  sha256: b6d05b7e6404b75974a3ed13466fd7ad963ad3eba6c8f591c1b3987a64100aa7
- location: https://download1.tixati.com/download/tixati-2.62-1.win64-install.exe
  sha256: 4670205a6bcfdb40a2df4279506d7bcd594a1fd5402eae8bb48bd11a0cdaf04d
  architecture: x64
