id: aptana-studio
name: Aptana Studio
version: 3.7.2.201807301111
repo: https://github.com/aptana/studio3/
installMethod: AdvancedInstaller
installers:
- location: https://github.com/aptana/studio3/releases/download/3.7.2.201807301111/Aptana_Studio_3_Setup.exe
  sha256: 5b3640243d3451514f2a6e869ea574a704590bbb8dfdd352bfd6c3d5993b173e
