id: youtube-dl
name: youtube-dl
version: 2020.01.24
home: https://yt-dl.org/
installMethod: Custom
installers:
- location: https://yt-dl.org/downloads/2020.01.24/youtube-dl.exe
  sha256: 4a3ae2d194418d478ae5903beda141bb1ed6f243b0bd0c8d6f0e167037a801af
