id: royal-server
name: Royal Server
version: 5.01.61114
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapplications.com/RoyalTS/RoyalTSInstaller_5.01.61114.0.msi
  sha256: 137b2e4a91bd8c67d9cbee635cff12ba231f508e1b5ec0742ec54185c5107aa8
