id: royal-server
name: Royal Server
version: 5.00.61221
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapplications.com/RoyalTS/RoyalTSInstaller_5.00.61221.0.msi
  sha256: 4e95e3ac8ce6f6e26dcedded529dfcf15b1173107c21a1c7070335ce2878a1c5
