id: royal-server
name: Royal Server
version: 5.00.61429
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapplications.com/RoyalTS/RoyalTSInstaller_5.00.61429.0.msi
  sha256: 283ed818179de7c812cf27fe26d24930b768f4dc74a2169a2e3d4d321d006009
