id: royal-server
name: Royal Server
version: 5.00.61314
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapplications.com/RoyalTS/RoyalTSInstaller_5.00.61314.0.msi
  sha256: 2ac370f5851c6a9ed2bacab3930d9d294581731525fdb61634b27b2228059a9f
