id: royal-server
name: Royal Server
version: 5.00.61322
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapplications.com/RoyalTS/RoyalTSInstaller_5.00.61322.0.msi
  sha256: b2d5f457269d27145357a0bba3f99c2a61705f13d25058a75b43f33617577905
