id: royal-server
name: Royal Server
version: 5.02.60304
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapplications.com/RoyalTS/RoyalTSInstaller_5.02.60304.0.msi
  sha256: 21549ca3d9ad0efbd4aaba8e3c820a9d8b95904e7478349b5e2c6374822a0e1d
