id: royal-server
name: Royal Server
version: 5.02.60406
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapps.com/RoyalTS/RoyalTSInstaller_5.02.60406.0.msi
  sha256: c68019d6d89ccce93d9e105f17ef4411ec6dd6dbc186aed41d665b02947a16a2
