id: royal-server
name: Royal Server
version: 5.00.61330
home: http://www.royal-server.com/
installMethod: MSI
installers:
- location: https://download.royalapplications.com/RoyalTS/RoyalTSInstaller_5.00.61330.0.msi
  sha256: 59794f60e92554dcf7a62c4016ec6d115e208d5820c26404faa5921e2eaad9b3
