id: adobe-download-manager
name: Adobe Download Manager
version: 2.0.0.363
home: https://www.adobe.com/
installMethod: Custom
installers:
- location: https://admdownload.adobe.com/bin/live/readerdc_br_fb_crd_install.exe
  architecture: x64
