id: mstream
name: mStream Express
version: 4.5.3
home: https://mstream.io/
repo: https://github.com/IrosTheBeggar/mStream/
license: GNU General Public License v3.0
installMethod: NSIS
installers:
- location: https://github.com/IrosTheBeggar/mStream/releases/download/v4.5.3/mStream-Server-Setup-4.5.3.exe
  sha256: 9290d03782eb32b5c8c7b7a26ce83cba213cb578ce86e715e86694fc4dba1e2f
