id: lisk-hub
name: Lisk Hub
version: 1.24.0
home: https://lisk.io/wallet
repo: https://github.com/LiskHQ/lisk-desktop/
license: GNU General Public License v3.0
installMethod: NSIS
installers:
- location: https://github.com/LiskHQ/lisk-desktop/releases/download/v1.24.0/lisk-win-1.24.0.exe
  sha256: e47631852f3cfa026aa929270bd576db29443a31dfa9b6bfd62df3202ebba942
