id: saola-animate
name: ActivePresenter
version: 7.5.8
home: https://atomisystems.com/saola-animate/
installMethod: Inno
installers:
- location: https://cdn.atomisystems.com/apdownloads/ActivePresenter_v7.5.8_setup.exe
  sha256: 0671f1ece8abb6cb942ef0cb3122e5db52f13b081cb73d1d93e97034322f2c93
