id: saola-animate
name: ActivePresenter
version: 7.5.11
home: https://atomisystems.com/saola-animate/
installMethod: Inno
installers:
- location: https://cdn.atomisystems.com/apdownloads/ActivePresenter_v7.5.11_setup.exe
  sha256: 06f8000e67b6fbe18cc2eaaa6dc8634c4a0b61158a80d2011ffc92c49e78d8f9
