id: saola-animate
name: ActivePresenter
version: 8.0.0
home: https://atomisystems.com/saola-animate/
installMethod: Inno
installers:
- location: https://cdn.atomisystems.com/apdownloads/ActivePresenter_v8.0.0_setup.exe
  sha256: 58179eacad90924edbddf3d2d1735c1510fa623fc573d96a86cf13ae00b0eedc
