id: saola-animate
name: ActivePresenter
version: 8.0.2
home: https://atomisystems.com/saola-animate/
installMethod: Inno
installers:
- location: https://cdn.atomisystems.com/apdownloads/ActivePresenter_v8.0.2_setup.exe
  sha256: 057527a89f40d343e7ea8e52a66895b15fdef09c91676caf96034afcf9af31b4
