id: phpstorm
name: PhpStorm
version: 201.7223.96
home: https://www.jetbrains.com/phpstorm/
installMethod: NSIS
installers:
- location: https://download.jetbrains.com/webide/PhpStorm-2020.1.1.exe
  sha256: a31652c5031c7d048f219a40a216bcccc1a00b9977c379a0ec5b86bdd51b2664
