id: google-drive
name: Google Drive
version: 1.3.33.23
home: https://www.google.com/drive/
installMethod: Custom
installers:
- location: https://dl.google.com/tag/s/appguid%3D{3C122445-AECE-4309-90B7-85A6AEF42AC0}%26iid%3D{9648D435-67BA-D2A7-54D2-1E0B5656BF03}%26ap%3Duploader%26appname%3DBackup%2520and%2520Sync%26needsadmin%3Dtrue/drive/installbackupandsync.exe
