id: altair-graphql-client
name: Altair GraphQL Client
version: 2.4.6.334
home: https://altair.sirmuel.design/
repo: https://github.com/imolorhe/altair/
license: MIT License
installMethod: NSIS
installers:
- location: https://github.com/imolorhe/altair/releases/download/v2.4.6/altair_2.4.6_win.exe
  sha256: 3d8dbbbe0be1f28a3a361cf0f954f113f0e34971361dd4b8acecd9108f99d25a
