id: wps-office
name: WPS Office
version: 11.2.0.9232
home: https://www.wps.com/office-free
installMethod: Custom
installers:
- location: https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/11.2.0.9232/WPSOffice_11.2.0.9232.exe
  sha256: 7785ecd9bfac59e67c0c2cb637e1f49ad97191d8a8020ef933040cff0f41f1ec
