id: videoredo-tvsuite
name: VideoReDo TVSuite V6
version: 6.60.10.816
home: https://www.videoredo.com/en/Products_TVSuite_V6.html
installMethod: Inno
installers:
- location: https://www.videoredo.com/en/Download.htm?download=tvsuitev6
