id: lyx
name: LyX
version: 2.3.4
home: https://www.lyx.org/
installMethod: NSIS
installers:
- location: https://ftp.lip6.fr/pub/lyx/bin/2.3.4/LyX-234-Installer-1.exe
  sha256: f07c1d655120b6dd375cc2fe8855285b901e4efd0380d1640870439a15351d54
