id: ao
name: Ao
version: 6.9.0.392
home: https://klaussinani.github.io/ao
repo: https://github.com/klaussinani/ao/
license: MIT License
installMethod: NSIS
installers:
- location: https://github.com/klaussinani/ao/releases/download/v6.9.0/ao-6.9.0.exe
  sha256: 171a29295264c16e11bb35ae31326d92a81bc77a35561a71fafbc192224c855c
- location: https://github.com/klaussinani/ao/releases/download/v6.9.0/ao-setup-6.9.0.exe
  sha256: 0864a2635d78fa8116d468173fbbc34cb871afba1fdea035031efd9492247813
