id: mongodb
name: MongoDB
version: 3.2.4
home: https://www.mongodb.com/
repo: https://github.com/mongodb/mongo/
license: AGPL v3
installMethod: MSI
installers:
- location: http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.2.4-signed.msi
  sha256: cdd553326044a8cd41287eb803dc7a490e2f106e618d58d4e46dd11c4ed7bfa0
  architecture: x64
