id: ethereum-mist
name: Ethereum Mist
version: 0.11.1
repo: https://github.com/ethereum/mist/
license: GNU General Public License v3.0
installMethod: NSIS
installers:
- location: https://github.com/ethereum/mist/releases/download/v0.11.1/Mist-installer-0-11-1.exe
  sha256: a2aec395019f2b05b3d0a245845868f425e4bc9d0407f0c415d96edf19b691a2
