id: clementine
name: Clementine
version: 1.4.0
home: https://www.clementine-player.org/
repo: https://github.com/clementine-player/Clementine/
license: GNU General Public License v3.0
installMethod: NSIS
installers:
- location: https://github.com/clementine-player/Clementine/releases/download/1.4.0rc1/ClementineSetup-1.4.0rc1.exe
  sha256: 6f9fa5ba31d414206d1e0d4058562402cc44d79307a465cf61726286b6ce8e5c
