id: adoptopenjdk-jdk-openj
name: AdoptOpenJDK JDK with Eclipse OpenJ9
version: 8.0.212.04
home: https://adoptopenjdk.net/
repo: https://github.com/AdoptOpenJDK/openjdk8-binaries/
installMethod: MSI
installers:
- location: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04/OpenJDK8U-jdk_x64_windows_hotspot_8u212b04.msi
  sha256: 22303c8338c8015ba34b21829706c1231dd966bd84372ce0de944c848bb13c52
  architecture: x64
- location: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04/OpenJDK8U-jre_x64_windows_hotspot_8u212b04.msi
  sha256: 3c82cb1fc8d367c8f69a788d45fdbf3a1b79d7130ee47745fa48d1e70189b7a2
  architecture: x64
