id: remote-desktop-manager
name: Remote Desktop Manager
version: 2019.2.21
home: https://remotedesktopmanager.com/
installMethod: AdvancedInstaller
installers:
- location: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2019.2.21.0.exe
  sha256: 202e2c0212509282ded509fb1eba325dde64ba94892c9b8f6b18e65798280955
