id: jitsi
name: Jitsi
version: 2.8.5426
home: https://desktop.jitsi.org/
repo: https://github.com/jitsi/jitsi/
license: Apache License 2.0
installMethod: MSI
installers:
- location: https://download.jitsi.org/jitsi/msi/jitsi-2.8.5426-x86.msi
  sha256: 015de91cf5c89335908b17020bddfae436e6cf8bcb490f3ddc8183fb20d195ee
- location: https://download.jitsi.org/jitsi/msi/jitsi-2.8.5426-x64.msi
  sha256: da8a85a039e62ef4563c3d576c4d2e12ed84db29bfd1bcec8b0e523776a5b358
  architecture: x64
