id: nomachine
name: NoMachine
version: 6.9.2
home: https://www.nomachine.com/
installMethod: Inno
installers:
- location: https://download.nomachine.com/download/6.9/Windows/nomachine_6.9.2_1.exe
  sha256: 890254b91ecd6a99da5386f3720b933162840f82cbf8a530f6c3fe239a8f6297
