id: intellij-idea-edu
name: IntelliJ IDEA Edu
version: 193.5233.131
home: https://www.jetbrains.com/pycharm-edu/
installMethod: NSIS
installers:
- location: https://download.jetbrains.com/idea/ideaIE-2019.3.exe
  sha256: 08aaf765f8f851111e1afc231592624d12264ac6514899c9d0df9b6e7b0b5b1c
