id: devdocs
name: DevDocs
version: 0.7.1
home: https://devdocs.egoist.sh/
repo: https://github.com/egoist/devdocs-desktop/
license: MIT License
installMethod: NSIS
installers:
- location: https://github.com/egoist/devdocs-desktop/releases/download/v0.7.1/DevDocs-0.7.1.exe
  sha256: aff4ef876903db48df117c3a06f221adda845a1963bbf9a5806120f93c5511ec
- location: https://github.com/egoist/devdocs-desktop/releases/download/v0.7.1/DevDocs-Setup-0.7.1.exe
  sha256: f7c8e51ce59167946c236b44a454e8726614139a23c87e4b9c7316995e8a54ab
