id: evga-precision-x1
name: EVGA Precision X1
version: 1.0.4
home: https://www.evga.com/precisionx1/
installMethod: NSIS
installers:
- location: https://www.evga.com/EVGA/GeneralDownloading.aspx?file=EVGA_Precision_X1_1.0.4.0.exe&survey=11.0.4.0
  sha256: dfed6be58f799dd6f9e35a9c61f503f23594e14c5a0e04fec7206c3b7dd741bc
