id: advanced-ip-scanner
name: Advanced IP Scanner
version: 2.5.3850
home: https://www.advanced-ip-scanner.com/
installMethod: Inno
installers:
- location: https://www.advanced-ip-scanner.com/download/Advanced_IP_Scanner_2.5.3850.exe
  sha256: 87bfb05057f215659cc801750118900145f8a22fa93ac4c6e1bfd81aa98b0a55
  minWindowsVersion: 10.0
