id: libreoffice
name: LibreOffice
version: 6.4.4.2
home: https://www.libreoffice.org/
repo: https://cgit.freedesktop.org/libreoffice
license: Mozilla Public License 2.0
installMethod: MSI
args:
  passive: REGISTER_NO_MSO_TYPES=1 ISCHECKFORPRODUCTUPDATES=0 ADDLOCAL=ALL
  silent: REGISTER_NO_MSO_TYPES=1 ISCHECKFORPRODUCTUPDATES=0 ADDLOCAL=ALL
installers:
- location: https://download.documentfoundation.org/libreoffice/stable/6.4.4/win/x86_64/LibreOffice_6.4.4_Win_x64.msi
  sha256: f145b203d5e427527d78fee6def0310fdaaae1b87d1728980544a450e2825fef
  architecture: x64
- location: https://download.documentfoundation.org/libreoffice/stable/6.4.4/win/x86/LibreOffice_6.4.4_Win_x86.msi
  sha256: 0f7694f31b87c2527781af86c840d0aa76c8afc22ccfe3959ff269328417922f
  architecture: x64
