id: android-studio
name: Android Studio
version: 3.6.3
home: https://developer.android.com/studio/
installMethod: NSIS
installers:
- location: https://redirector.gvt1.com/edgedl/android/studio/install/3.6.3.0/android-studio-ide-192.6392135-windows.exe
  sha256: 07b6df807fda59e69f05b85ff6f6bd0c70d09e57fb151197155ef5f115f96e59
