id: android-studio
name: Android Studio
version: 3.6.2
home: https://developer.android.com/studio/
installMethod: NSIS
installers:
- location: https://redirector.gvt1.com/edgedl/android/studio/install/3.6.2.0/android-studio-ide-192.6308749-windows.exe
  sha256: 977112d05392fdb0e74ebffe33d05e844d084b5015a31151796a30324f855a35
