id: mkvtoolnix
name: MKVToolNix
version: 43.0
home: https://mkvtoolnix.download/
installMethod: NSIS
installers:
- location: https://mkvtoolnix.download/windows/releases/43.0.0/mkvtoolnix-32-bit-43.0.0-setup.exe
  sha256: 28f850d2ea0271cbcdbc0f8672c0d3cee2bdee5d9e466012b366efa6e8f74202
  minWindowsVersion: 6.1
- location: https://mkvtoolnix.download/windows/releases/43.0.0/mkvtoolnix-64-bit-43.0.0-setup.exe
  sha256: 22a55c51ed7eb1a4ed2d2c8196aaab0eab730483885bc67bf4a00290ae67fa1c
  architecture: x64
  minWindowsVersion: 6.1
