id: mindmapp
name: Mindmapp
version: 2.5.6
home: https://mindmapp.cedoor.org/
repo: https://github.com/Mindmapp/mindmapp/
license: MIT License
installMethod: NSIS
installers:
- location: https://github.com/samuelmeuli/mini-diary/releases/download/v2.5.6/Mini-Diary-Setup-2.5.6.exe
  sha256: fe65a8120978a9dddad4db1ae2697c99564eec8c6f718c35ac7fb11e7a2ab890
