id: mindmapp
name: Mindmapp
version: 2.4.3
home: https://mindmapp.cedoor.org/
repo: https://github.com/Mindmapp/mindmapp/
license: MIT License
installMethod: NSIS
installers:
- location: https://github.com/samuelmeuli/mini-diary/releases/download/v2.4.3/Mini-Diary-Setup-2.4.3.exe
  sha256: 97d6108c8c778d4241ab84493a7e504ab6ba38c81211562fefc0210cad444387
